// Workshop
export const CREATE_WORKSHOP = 'CREATE_WORKSHOP';
export const UPDATE_WORKSHOP = 'UPDATE_WORKSHOP';
export const GET_LOCATIONS = 'GET_LOCATIONS';
export const GET_WORKSHOPS_BY_CITY = 'GET_WORKSHOPS_BY_CITY';
export const UPDATE_CURRENT_WORKSHOP = 'UPDATE_CURRENT_WORKSHOP';
export const TOGGLE_SOLDOUT = 'TOGGLE_SOLDOUT';
export const CLEAR_WORKSHOPS_DATA = 'CLEAR_WORKSHOPS_DATA';
export const SET_PARTICIPANT = 'SET_PARTICIPANT';
export const CLEAR_PARTICIPANT = 'CLEAR_PARTICIPANT';
export const REMOVE_PARTICIPANT_FROM_WORKSHOP = 'REMOVE_PARTICIPANT_FROM_WORKSHOP';
export const APPROVE_USER = 'APPROVE_USER';

// Admin
export const ADMIN_SIGNED_IN = 'ADMIN_SIGNED_IN';
export const SIGN_IN_FAILED = 'SIGN_IN_FAILED';

// Coupon
export const CREATE_NEW_COUPON = 'CREATE_NEW_COUPON';
export const CLEAR_COUPON_DATA = 'CLEAR_COUPON_DATA';
export const UPDATE_ALL_COUPONS = 'UPDATE_ALL_COUPONS';
export const SET_CURRENT_COUPON = 'SET_CURRENT_COUPON';
export const EDIT_COUPON = 'EDIT_COUPON';
